# Credit Risk Evaluator

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix, classification_report

## Retrieve the Data

The data is located in the Challenge Files Folder:

* `lending_data.csv`

Import the data using Pandas. Display the resulting dataframe to confirm the import was successful.

In [2]:
# Import the data
file_path = Path("Resources/lending_data.csv")

In [3]:
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

In [4]:
# Check for missing values
print(df.count())
print(df.isnull().values.any())

loan_size           77536
interest_rate       77536
borrower_income     77536
debt_to_income      77536
num_of_accounts     77536
derogatory_marks    77536
total_debt          77536
loan_status         77536
dtype: int64
False


In [5]:
# Data Exploration
df["loan_status"].unique()

array([0, 1], dtype=int64)

In [6]:
# Summary Statistics
df.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt   loan_status  
count     77536.000000      77536.000000  77536.000000  77536.000000  
mean          3.826610          0.392308  19221.949804      0.032243  
std           1.904426          0.582086   8371.635077      0.176646  
min           0.000000          0.000000      0.000000      0.000000  
25%           3.000000          0.000000  14800.000000      0.000000  
50%           4.000000          0.000000  18100.000000      0.000000  
75%           4.000000          1.000000  21400.000000      0.000000  
max          16.000000          3.000000  75200.000000      1.000000

In [7]:
df.dtypes

loan_size           float64
interest_rate       float64
borrower_income       int64
debt_to_income      float64
num_of_accounts       int64
derogatory_marks      int64
total_debt            int64
loan_status           int64
dtype: object

In [8]:
# Define the X (features) and y (target) sets
X = df.drop("loan_status", axis=1)
y = df["loan_status"].values

## Predict Model Performance

You will be creating and comparing two models on this data: a Logistic Regression, and a Random Forests Classifier. Before you create, fit, and score the models, make a prediction as to which model you think will perform better. You do not need to be correct! 

Write down your prediction in the designated cells in your Jupyter Notebook, and provide justification for your educated guess.

### Prediction: 
I think the Logistic Regression would perform better than the Random Forest Classifier as its predictions would be based on the full set of cases (with more records in either classification category) as compared to the Random Forest Classifier that will re-sample the data multiple times and build several smaller decision trees. Furthermore, given that most of the features in the data set are continuous and numeric in nature, I'm guessing that a regression that produces a linear model has greater accuracy.

## Split the Data into Training and Testing Sets

In [9]:
# Split the data into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train.head()

loan_size  interest_rate  borrower_income  debt_to_income  \
63243     8900.0          6.893            45500        0.340659   
36991     9000.0          6.932            45800        0.344978   
39985     8900.0          6.896            45500        0.340659   
63047     9000.0          6.961            46100        0.349241   
49913     8400.0          6.712            43800        0.315068   

       num_of_accounts  derogatory_marks  total_debt  
63243                3                 0       15500  
36991                3                 0       15800  
39985                3                 0       15500  
63047                3                 0       16100  
49913                3                 0       13800

## Create, Fit and Compare Models

Create a Logistic Regression model, fit it to the data, and print the model's score. Do the same for a Random Forest Classifier. You may choose any starting hyperparameters you like. 

Which model performed better? How does that compare to your prediction? Write down your results and thoughts in the designated markdown cell.

In [10]:
# Scale

scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
# Train a Logistic Regression model and print the model score

#Create a logistic regression model
LR = LogisticRegression()
LR

LogisticRegression()

In [12]:
#Fit our model by using training data
LR.fit(X_train_scaled, y_train)
print(f"Training Data Score: {LR.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {LR.score(X_test_scaled, y_test)}")

Training Data Score: 0.9941188609162196
Testing Data Score: 0.9941704498555509


In [13]:
y_pred = LR.predict(X_test_scaled)
confusion_matrix(y_test,y_pred)

array([[18690,   102],
       [   11,   581]], dtype=int64)

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18792
           1       0.85      0.98      0.91       592

    accuracy                           0.99     19384
   macro avg       0.93      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384



In [15]:
# Train a Random Forest Classifier model and print the model score
clf = RandomForestClassifier(random_state=1, n_estimators=50).fit(X_train_scaled, y_train)
print(f'Training Score: {clf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {clf.score(X_test_scaled, y_test)}')

Training Score: 0.9971798046498831
Testing Score: 0.9917457697069748


In [16]:
y_pred2 = clf.predict(X_test_scaled)
confusion_matrix(y_test,y_pred2)

array([[18695,    97],
       [   63,   529]], dtype=int64)

In [17]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18792
           1       0.85      0.89      0.87       592

    accuracy                           0.99     19384
   macro avg       0.92      0.94      0.93     19384
weighted avg       0.99      0.99      0.99     19384



## Which model performed better? How does that compare to your prediction? 

The accuracy of both models were similiar in performance. Upon closer inspection of other metrics, it seems that the Logistic Regression model has the slight edge in terms of sensitivity (i.e., a higher percentage of actual positive results being predicted correctly). The F1 score was also greater for the Logistic Regression Model. Thus, the results suggest that the Logistic Regression Model performed better that the Random Forest Classifier and my prediction is correct.